<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="test-absen.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW dbg_scanlogscan_date CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogtgl CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogjam CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpin CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpegawai_nip CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpegawai_nama CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpembagian1_nama CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpembagian2_nama CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogpembagian3_nama CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogverifymode CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanloginoutmode CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogwork_code CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogsn CDATA #IMPLIED>
  <!ATTLIST ROW dbg_scanlogdevice_name CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="dbg_scanlogscan_date" Caption="Tanggal scan" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="109"></COLUMN>
    <COLUMN Name="dbg_scanlogtgl" Caption="Tanggal" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="64"></COLUMN>
    <COLUMN Name="dbg_scanlogjam" Caption="Jam" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="50"></COLUMN>
    <COLUMN Name="dbg_scanlogpin" Caption="PIN" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="38"></COLUMN>
    <COLUMN Name="dbg_scanlogpegawai_nip" Caption="NIP" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="38"></COLUMN>
    <COLUMN Name="dbg_scanlogpegawai_nama" Caption="Nama" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="133"></COLUMN>
    <COLUMN Name="dbg_scanlogpembagian1_nama" Caption="Jabatan" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="61"></COLUMN>
    <COLUMN Name="dbg_scanlogpembagian2_nama" Caption="Divisi" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="dbg_scanlogpembagian3_nama" Caption="Kantor" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="66"></COLUMN>
    <COLUMN Name="dbg_scanlogverifymode" Caption="Verifikasi" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="68"></COLUMN>
    <COLUMN Name="dbg_scanloginoutmode" Caption="I/O" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="36"></COLUMN>
    <COLUMN Name="dbg_scanlogwork_code" Caption="Workcode" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="72"></COLUMN>
    <COLUMN Name="dbg_scanlogsn" Caption="SN" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="114"></COLUMN>
    <COLUMN Name="dbg_scanlogdevice_name" Caption="Mesin" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="66"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW dbg_scanlogscan_date="2022-07-27T19:27:59" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="19:27:59" dbg_scanlogpin="1060" dbg_scanlogpegawai_nip="07" dbg_scanlogpegawai_nama="Nur Aeni Arifin" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Corporate Finance" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T18:51:54" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="18:51:54" dbg_scanlogpin="1060" dbg_scanlogpegawai_nip="07" dbg_scanlogpegawai_nama="Nur Aeni Arifin" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Corporate Finance" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:19:16" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:19:16" dbg_scanlogpin="1060" dbg_scanlogpegawai_nip="07" dbg_scanlogpegawai_nama="Nur Aeni Arifin" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Corporate Finance" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T10:32:39" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="10:32:39" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T18:22:19" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="18:22:19" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T13:00:56" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="13:00:56" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T18:41:43" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="18:41:43" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="3" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T09:59:49" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="09:59:49" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T19:27:41" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="19:27:41" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T11:49:56" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="11:49:56" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T18:45:37" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="18:45:37" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T11:39:02" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="11:39:02" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:19:46" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:19:46" dbg_scanlogpin="1070" dbg_scanlogpegawai_nip="08" dbg_scanlogpegawai_nama="Primaveira Prameswari" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T08:16:56" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="08:16:56" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T18:10:54" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="18:10:54" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T07:27:57" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="07:27:57" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T17:01:11" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="17:01:11" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T07:01:05" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="07:01:05" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T16:58:22" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="16:58:22" dbg_scanlogpin="1080" dbg_scanlogpegawai_nip="14" dbg_scanlogpegawai_nama="Febri Lukmantory Subagio" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Jupiter-Deni K" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T09:30:42" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="09:30:42" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T18:18:28" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="18:18:28" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T09:34:45" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="09:34:45" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T18:34:23" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="18:34:23" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T09:22:56" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="09:22:56" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T18:22:27" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="18:22:27" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T09:22:52" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="09:22:52" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T18:48:47" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="18:48:47" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T09:17:09" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="09:17:09" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:19:32" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:19:32" dbg_scanlogpin="1120" dbg_scanlogpegawai_nip="48" dbg_scanlogpegawai_nama="Adila Triana Putri" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T08:22:56" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="08:22:56" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T21:51:04" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="21:51:04" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T07:45:41" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="07:45:41" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T13:51:00" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="13:51:00" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T00:02:42" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="00:02:42" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T14:01:54" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="14:01:54" dbg_scanlogpin="1150" dbg_scanlogpegawai_nip="58" dbg_scanlogpegawai_nama="Dhanar Prastya Armadi" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Vesta-David" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T08:37:31" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="08:37:31" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T18:07:20" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="18:07:20" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T08:44:07" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="08:44:07" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T18:04:54" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="18:04:54" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T09:04:01" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="09:04:01" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T18:21:01" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="18:21:01" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T08:33:41" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="08:33:41" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:00:46" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:00:46" dbg_scanlogpin="1200" dbg_scanlogpegawai_nip="100" dbg_scanlogpegawai_nama="M David Kurniawan" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T10:00:00" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="10:00:00" dbg_scanlogpin="1210" dbg_scanlogpegawai_nip="107" dbg_scanlogpegawai_nama="Masiffah Mahardika Jusuf" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:10:15" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:10:15" dbg_scanlogpin="1210" dbg_scanlogpegawai_nip="107" dbg_scanlogpegawai_nama="Masiffah Mahardika Jusuf" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="COO" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T09:31:18" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="09:31:18" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T18:23:39" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="18:23:39" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T09:07:52" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="09:07:52" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T18:14:02" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="18:14:02" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T09:33:16" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="09:33:16" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T18:21:10" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="18:21:10" dbg_scanlogpin="1290" dbg_scanlogpegawai_nip="133" dbg_scanlogpegawai_nama="Moh Rizka Haris Pradana" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="Order Management" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="2" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-25T11:04:19" dbg_scanlogtgl="2022-07-25" dbg_scanlogjam="11:04:19" dbg_scanlogpin="1310" dbg_scanlogpegawai_nip="148" dbg_scanlogpegawai_nama="Erda Widya Kusuma" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-26T09:37:20" dbg_scanlogtgl="2022-07-26" dbg_scanlogjam="09:37:20" dbg_scanlogpin="1310" dbg_scanlogpegawai_nip="148" dbg_scanlogpegawai_nama="Erda Widya Kusuma" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-27T09:46:09" dbg_scanlogtgl="2022-07-27" dbg_scanlogjam="09:46:09" dbg_scanlogpin="1310" dbg_scanlogpegawai_nip="148" dbg_scanlogpegawai_nama="Erda Widya Kusuma" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-28T09:32:39" dbg_scanlogtgl="2022-07-28" dbg_scanlogjam="09:32:39" dbg_scanlogpin="1310" dbg_scanlogpegawai_nip="148" dbg_scanlogpegawai_nama="Erda Widya Kusuma" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>
    <ROW dbg_scanlogscan_date="2022-07-29T10:00:21" dbg_scanlogtgl="2022-07-29" dbg_scanlogjam="10:00:21" dbg_scanlogpin="1310" dbg_scanlogpegawai_nip="148" dbg_scanlogpegawai_nama="Erda Widya Kusuma" dbg_scanlogpembagian1_nama="" dbg_scanlogpembagian2_nama="RM" dbg_scanlogpembagian3_nama="Head Office" dbg_scanlogverifymode="1" dbg_scanloginoutmode="1" dbg_scanlogwork_code="0" dbg_scanlogsn="FIO616202019511909" dbg_scanlogdevice_name="Head Office"></ROW>